"""Creating tables

Revision ID: e9b5dcf4f824
Revises: ffdc0a98111c
Create Date: 2023-05-30 23:08:53.756802

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'e9b5dcf4f824'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),

    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50)),
    sa.Column('artists', sa.String(length=100)),
    sa.Column('genre', sa.String(length=20)),
    sa.Column('description', sa.String(length=255)),
    sa.Column('audio_url', sa.String(length=255)),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'] ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE songs SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###